<?php

namespace Nextras\Dbal\Bridges\NetteTracy;

?>
<style class="tracy-debug">
	#tracy-debug .nextras-dbal-panel-sql { background: white !important; }
	#tracy-debug .nextras-dbal-panel-sql .tracy-toggle, #tracy-debug .nextras-dbal-panel-sql a { color: #777 !important; }
	#tracy-debug .nextras-dbal-panel-sql .nextras-dbal-rowscount { color: #777 !important; margin-right: 1em !important; }
	#tracy-debug .nextras-dbal-panel-sql .tracy-toggle:hover { color: #fff !important; }
	#tracy-debug .nextras-dbal-panel-sql .whitespace-explain { white-space: pre; !important; }
	#tracy-debug .nextras-dbal-panel-time { text-align: right !important; }
</style>

<script>
	function nextrasDbalPanelCopySql(containerid) {
		if (document.selection) { // IE
			var range = document.body.createTextRange();
			range.moveToElementText(document.getElementById(containerid));
			range.select();
		} else if (window.getSelection) {
			var range = document.createRange();
			range.selectNode(document.getElementById(containerid));
			window.getSelection().removeAllRanges();
			window.getSelection().addRange(range);
		}
		document.execCommand("copy");
	}
</script>

<h1>Queries: <?php echo $count ?></h1>
<div class="tracy-inner nextras-dbal-panel">
	<table>
		<tr>
			<th class="nextras-dbal-panel-time">ms</th>
			<th>SQL query</th>
		</tr>
		<?php
		foreach ($queries as $query):
			list(, $sql, $elapsedTime, $rowsCount, $explain) = $query;
			$uniqRowId = uniqid('row-');
		?>
		<tr>
		<td class="nextras-dbal-panel-time"><?php echo $elapsedTime ? sprintf('%0.2f', $elapsedTime * 1000) : '' ?></td>
		<td class="nextras-dbal-panel-sql">
			<span id="<?php echo $uniqRowId; ?>"><?php echo $sql ?></span>
			<?php if ($explain !== null || $rowsCount !== null): ?><br><?php endif; ?>
			<?php if ($rowsCount !== null): ?>
				<span class="nextras-dbal-rowscount"><?php echo $rowsCount === 1 ? $rowsCount . ' row' : $rowsCount . ' rows' ?></span>
			<?php endif; ?>
			<span class="nextras-dbal-rowscount"><a onclick="nextrasDbalPanelCopySql('<?php echo $uniqRowId; ?>')">copy</a></span>
			<?php if ($explain !== null): ?>
				<a class="tracy-toggle tracy-collapsed" data-tracy-ref="^tr .nextras-dbal-explain">explain</a>
				<table class="tracy-collapsed nextras-dbal-explain">
					<tr>
					<?php foreach ($explain[0] as $col => $foo): ?>
						<th><?php echo htmlSpecialChars($col, ENT_NOQUOTES, 'UTF-8') ?></th>
					<?php endforeach ?>
					</tr>
					<?php foreach ($explain as $row): ?>
					<tr>
						<?php foreach ($row as $col): ?>
						<td class="<?php echo $whitespaceExplain ? 'whitespace-explain' : '' ?>"><?php echo htmlSpecialChars($col, ENT_NOQUOTES, 'UTF-8') ?></td>
						<?php endforeach ?>
					</tr>
					<?php endforeach ?>
				</table>
			<?php endif; ?>
		</td>
		</tr>
		<?php endforeach ?>
	</table>
	<?php if (count($queries) < $count): ?><p>...and more</p><?php endif ?>
</div>
